

# Setting user
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.user.role=ADMIN


server:
  port: 9080
  servlet:
    context-path: "/backend"


#GCP MYSQL Configuration
#Requires default auth configured! -> set service account key as ENV var -> { GOOGLE_APPLICATION_CREDENTIALS = /path/to/key.json}spring:
spring:
  datasource:
    username: root
    password: Kagami2@
    url: jdbc:mysql://google/site1-database?cloudSqlInstance=ivory-cycle-412111:us-central1:mysql-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    hikari:
      maximum-pool-size: 10
  cloud:
    gcp:
      credentials:
        location: "./credentials/ivory-cycle-412111-b5503cd575ba.json"


  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      use_sql_comments: true

    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG
    com:
      zaxxer:
        hikari: DEBUG


#logging:
#  level:
#    org:
#      hibernate:
#        SQL: info



# Logging configs
#logging.level.com.better.backend_app = TRACE
#logging.pattern.console=%d [%level] %c{1.} [%t] %m%n
#logging.file = appLog.log
#logging.pattern.file=%d [%level] %c{1.} %m%n



#logging.level.org.springframework.security=DEBUG







