

# Setting user
#spring.security.user.name=admin
#spring.security.user.password=admin123
#spring.security.user.role=ADMIN


server:
  port: 9080
  servlet:
    context-path: "/backend"


spring:
  datasource:
    url: jdbc:mysql://mysql-leakdg-service.mysql-operator.svc.cluster.local/squid_corals_backend
    username: root
    password: Kagami2@


  # Logging configs
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      use_sql_comments: true

    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL:
          INFO
    com:
      zaxxer:
        hikari: DEBUG